import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Terms of Service — PathWise",
  description: "PathWise terms of service and conditions of use.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-700 mb-10"
        >
          <ArrowLeft size={15} />
          Back to PathWise
        </Link>

        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-slate-400 mb-10">Last updated: 1 April 2025</p>

        <div className="prose prose-slate max-w-none text-sm leading-relaxed space-y-8">

          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">1. Acceptance of Terms</h2>
            <p className="text-slate-600">
              By creating a PathWise account or using any part of the service, you agree to these
              Terms of Service. If you do not agree, please do not use PathWise. These terms form a
              binding agreement between you and PathWise.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">2. What PathWise Provides</h2>
            <p className="text-slate-600">
              PathWise is a career-guidance platform that uses machine learning and AI to generate
              personalised career recommendations, skill-gap analyses, and learning roadmaps based on
              information you provide. The service is intended to support your decision-making, not
              replace professional career counselling or employment advice.
            </p>
            <p className="text-slate-600 mt-3">
              Career data, salary ranges, and job-demand figures are estimates drawn from publicly
              available sources and are updated periodically. PathWise makes no guarantee that any
              career recommendation will lead to employment.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">3. Your Account</h2>
            <p className="text-slate-600">
              You are responsible for keeping your login credentials secure and for all activity that
              occurs under your account. You must be at least 13 years old to create an account. If
              you are under 18, please review these terms with a parent or guardian.
            </p>
            <p className="text-slate-600 mt-3">
              You agree to provide accurate information when creating your profile. Misleading or
              false information may result in inaccurate recommendations and is grounds for account
              termination.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">4. Acceptable Use</h2>
            <p className="text-slate-600">You agree not to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1 text-slate-600">
              <li>Use PathWise for any unlawful purpose</li>
              <li>Attempt to reverse-engineer, scrape, or extract data from the platform at scale</li>
              <li>Submit content that is abusive, hateful, or infringes on the rights of others</li>
              <li>Share your account credentials with third parties</li>
              <li>Use automated tools to generate large volumes of requests</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">5. Intellectual Property</h2>
            <p className="text-slate-600">
              All PathWise software, design, copy, and data compilations are owned by PathWise or its
              licensors. You may not reproduce, redistribute, or create derivative works from them
              without written permission.
            </p>
            <p className="text-slate-600 mt-3">
              Profile data and roadmaps you generate belong to you. You grant PathWise a limited
              licence to store and process this data solely to provide the service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">6. AI-Generated Content</h2>
            <p className="text-slate-600">
              Career recommendations, roadmaps, and advisor chat responses are generated by
              AI models. While we work to make these outputs accurate and helpful, they may
              occasionally contain errors or outdated information. Always verify important career
              decisions with additional sources and, where appropriate, a qualified professional.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">7. Disclaimers and Limitation of Liability</h2>
            <p className="text-slate-600">
              PathWise is provided "as is" without warranties of any kind. To the fullest extent
              permitted by law, PathWise is not liable for any indirect, incidental, or consequential
              damages arising from your use of the service, including employment outcomes.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">8. Termination</h2>
            <p className="text-slate-600">
              You may delete your account at any time. PathWise may suspend or terminate access if
              you violate these terms. Upon termination, your profile data will be deleted in
              accordance with our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">9. Changes to These Terms</h2>
            <p className="text-slate-600">
              We may update these terms from time to time. When we do, we will revise the "Last
              updated" date above. Continued use of PathWise after changes take effect constitutes
              acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">10. Contact</h2>
            <p className="text-slate-600">
              Questions about these terms? Email us at{" "}
              <a href="mailto:hello@pathwise.app" className="text-brand-600 hover:underline">
                hello@pathwise.app
              </a>
              .
            </p>
          </section>

          <div className="pt-6 border-t border-slate-100 text-xs text-slate-400">
            <Link href="/privacy" className="hover:text-slate-600 underline">Privacy Policy</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
