// ─────────────────────────────────────────────
// Tool: explainRecommendation
//
// Explains WHY a career was recommended to this
// user. Reads Claude's own reasoning from the
// stored recommendation — so the explanation is
// grounded in what the AI actually decided, not
// reconstructed after the fact.
// ─────────────────────────────────────────────

import type { ToolResult, ExplainRecommendationData } from "../types";
import { getStudentProfile } from "./get-student-profile";
import { resolveCareer } from "./get-career-details";
import { getStoredRecommendations } from "@/lib/agent/store";
import { computeSkillOverlap } from "@/lib/agent/recommend";

export async function explainRecommendation(
  userId: string,
  careerId: string
): Promise<ToolResult<ExplainRecommendationData>> {
  const career = resolveCareer(careerId);
  if (!career) {
    return {
      success: false,
      error: `Career "${careerId}" was not found in the PathWise library.`,
      source: "memory",
    };
  }

  const profileResult = await getStudentProfile(userId);
  if (!profileResult.success || !profileResult.data) {
    return {
      success: false,
      error: profileResult.error ?? "Could not load student profile.",
      source: "computed",
    };
  }

  // Pull Claude's own recommendation data — the explanation IS what Claude decided
  const stored = getStoredRecommendations(userId);
  const aiRec = stored?.recommendations.find((r) => r.career_id === career.id);

  if (aiRec) {
    return {
      success: true,
      data: {
        careerId: career.id,
        careerTitle: career.title,
        score: aiRec.match_score,
        reasons: aiRec.match_reasons,
        matchedSkills: aiRec.matching_skills,
        missingSkills: aiRec.skill_gaps,
        scoreNote:
          "This score and reasoning were generated by Claude based on your full profile — skills, interests, goals, work style, and preferred industries.",
      },
      source: "computed",
    };
  }

  // Not in store — compute a factual overlap and surface it
  const overlap = computeSkillOverlap(
    profileResult.data.skills,
    career.required_skills
  );

  const score =
    career.required_skills.length > 0
      ? Math.round((overlap.matched.length / career.required_skills.length) * 100)
      : 0;

  return {
    success: true,
    data: {
      careerId: career.id,
      careerTitle: career.title,
      score,
      reasons: [
        overlap.matched.length > 0
          ? `You already have ${overlap.matched.length} of the required skills: ${overlap.matched.slice(0, 3).join(", ")}.`
          : "This career aligns with your stated interests and goals.",
        `You have ${overlap.gaps.length} skill gaps to close before being job-ready.`,
      ],
      matchedSkills: overlap.matched,
      missingSkills: overlap.gaps,
      scoreNote:
        "Complete your profile and generate recommendations for a full AI-powered explanation.",
    },
    source: "memory",
  };
}
